spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/producto_db
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      root: INFO
      com.atz.microservice: WARN
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file:
      name: logs/producto-microservice.log
      max-size: 10MB
      max-history: 30
server:
  port: 8095